# Generated by Django 4.2.7 on 2025-09-25 04:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_cycle_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current hours used in 8-day cycle (0-70)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "current_daily_drive_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily driving hours used (0-11)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "current_daily_duty_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily on-duty hours used (0-14)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "total_distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "estimated_fuel_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_as_current",
                        to="core.location",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="core.driver",
                    ),
                ),
                (
                    "dropoff_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_as_dropoff",
                        to="core.location",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_as_pickup",
                        to="core.location",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "trips_trip",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("rest", "Rest Break"),
                            ("fuel", "Fuel Stop"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("mandatory_break", "Mandatory Break"),
                            ("meal", "Meal Break"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence_order", models.PositiveIntegerField()),
                ("estimated_arrival_time", models.DateTimeField()),
                ("estimated_departure_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("is_mandatory", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="core.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trips_stop",
                "ordering": ["trip", "sequence_order"],
                "unique_together": {("trip", "sequence_order")},
            },
        ),
        migrations.CreateModel(
            name="FuelStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diesel_price_per_gallon",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "estimated_fuel_gallons",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "estimated_fuel_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("has_parking", models.BooleanField(default=True)),
                ("has_restrooms", models.BooleanField(default=True)),
                ("has_food", models.BooleanField(default=False)),
                ("has_showers", models.BooleanField(default=False)),
                ("has_truck_wash", models.BooleanField(default=False)),
                ("station_name", models.CharField(blank=True, max_length=100)),
                ("station_brand", models.CharField(blank=True, max_length=50)),
                (
                    "stop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_details",
                        to="trips.stop",
                    ),
                ),
            ],
            options={
                "db_table": "trips_fuel_stop",
            },
        ),
        migrations.CreateModel(
            name="RouteSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence_order", models.PositiveIntegerField()),
                ("distance_miles", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "estimated_time_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "end_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_as_end",
                        to="core.location",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_as_start",
                        to="core.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_segments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trips_route_segment",
                "ordering": ["trip", "sequence_order"],
                "unique_together": {("trip", "sequence_order")},
            },
        ),
    ]
