# Generated by Django 4.2.7 on 2025-09-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("dot_number", models.CharField(max_length=20, unique=True)),
                ("mc_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "core_company",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_state", models.CharField(max_length=2)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_driver",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("license_plate", models.CharField(max_length=20)),
                ("license_state", models.CharField(max_length=2)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("fuel_capacity", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "mpg",
                    models.DecimalField(decimal_places=1, default=6.5, max_digits=4),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_vehicle",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=500)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(default="USA", max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "core_location",
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="core_locati_latitud_367ccc_idx",
                    )
                ],
            },
        ),
    ]
