# Generated by Django 4.2.7 on 2025-09-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "total_distance_miles",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "estimated_time_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "average_speed",
                    models.DecimalField(decimal_places=1, default=60, max_digits=4),
                ),
                ("avoid_tolls", models.BooleanField(default=False)),
                ("truck_route", models.BooleanField(default=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "end_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_templates_as_end",
                        to="core.location",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_templates_as_start",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "routes_template",
                "ordering": ["-times_used", "name"],
            },
        ),
        migrations.CreateModel(
            name="RestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("truck_parking_spaces", models.PositiveIntegerField(default=0)),
                ("car_parking_spaces", models.PositiveIntegerField(default=0)),
                ("is_24_hours", models.BooleanField(default=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("amenities", models.JSONField(default=list)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "diesel_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("price_updated", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_area",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "routes_rest_area",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence_order", models.PositiveIntegerField()),
                (
                    "waypoint_type",
                    models.CharField(
                        choices=[
                            ("start", "Start Point"),
                            ("waypoint", "Waypoint"),
                            ("fuel", "Fuel Stop"),
                            ("rest", "Rest Area"),
                            ("end", "End Point"),
                        ],
                        default="waypoint",
                        max_length=20,
                    ),
                ),
                ("stop_duration_minutes", models.PositiveIntegerField(default=0)),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_waypoints",
                        to="core.location",
                    ),
                ),
                (
                    "route_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="routes.routetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "routes_waypoint",
                "ordering": ["route_template", "sequence_order"],
                "unique_together": {("route_template", "sequence_order")},
            },
        ),
        migrations.CreateModel(
            name="RouteAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("CONSTRUCTION", "Construction"),
                            ("ACCIDENT", "Accident"),
                            ("WEATHER", "Weather Alert"),
                            ("ROAD_CLOSURE", "Road Closure"),
                            ("TRAFFIC_JAM", "Traffic Jam"),
                            ("FUEL_SHORTAGE", "Fuel Shortage"),
                            ("INSPECTION", "DOT Inspection"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_duration_hours",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("estimated_delay_minutes", models.PositiveIntegerField(default=0)),
                ("affects_trucks", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_alerts",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "routes_alert",
                "ordering": ["-start_time", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["location", "is_active"],
                        name="routes_aler_locatio_00d2b6_idx",
                    ),
                    models.Index(
                        fields=["start_time", "end_time"],
                        name="routes_aler_start_t_3cabd9_idx",
                    ),
                ],
            },
        ),
    ]
